name: Deploy PAAS environment

inputs:
  environment_name:
    description: The name of the environment
    required: true
  azure_credentials:
    description: JSON object containing a service principal that can read from Azure Key Vault
    required: true

runs:
  using: composite

  steps:
    - uses: Azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.10
        terraform_wrapper: false

    - name: Set environment variables
      shell: bash
      run: |
        tf_vars_file=terraform/workspace_variables/${{ inputs.environment_name }}.tfvars.json
        echo "KEY_VAULT_NAME=$(jq -r '.key_vault_name' ${tf_vars_file})" >> $GITHUB_ENV

    - uses: Azure/get-keyvault-secrets@v1
      id: get_secrets
      with:
        keyvault: ${{ env.KEY_VAULT_NAME }}
        secrets: 'TFSTATE-CONTAINER-ACCESS-KEY'

    - name: Terraform
      run: make ci ${{ inputs.environment_name }} terraform-apply
      env:
        ARM_ACCESS_KEY: ${{ steps.get_secrets.outputs.TFSTATE-CONTAINER-ACCESS-KEY }}
        TF_VAR_azure_sp_credentials_json: ${{ inputs.azure_credentials }}
      shell: bash
