name: Build

on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
    paths-ignore:
    - 'README.md'

jobs:
  deploy_dev:
    name: Deploy to dev environment
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    environment: dev
    strategy:
      matrix:
        url: ["https://prometheus-tra-monitoring-dev.london.cloudapps.digital/api/v1/status/buildinfo", "https://alertmanager-tra-monitoring-dev.london.cloudapps.digital/", "https://grafana-tra-monitoring-prod.london.cloudapps.digital/" ]
    steps:
    - uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.10

    - name: Check formatting
      run: terraform fmt -check
      working-directory: terraform

    - name: Validate
      run: |
        terraform init -backend=false
        terraform validate -no-color
      working-directory: terraform

    - name: Deploy to dev environment
      uses: ./.github/workflows/actions
      with:
        environment_name: dev
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Integration Test
      uses: wei/curl@master
      with:
        args: ${{ matrix.url }}


  deploy_prod:
    name: Deploy to prod environment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: deploy_dev
    environment: prod
    steps:
    - uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.10

    - name: Validate
      run: |
        terraform init -backend=false
        terraform validate -no-color
      working-directory: terraform

    - name: Deploy to prod environment
      uses: ./.github/workflows/actions
      with:
        environment_name: prod
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
