name: Build

on:
  push:
    branches:
    - dev
    paths-ignore:
    - README.md

jobs:
  deploy_dev:
    name: Deploy to dev environment
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.10

    - name: Check formatting
      run: terraform fmt -check
      working-directory: terraform

    - name: Validate
      run: |
        terraform init -backend=false
        terraform validate -no-color
      working-directory: terraform

    - name: Deploy to dev environment
      uses: ./.github/workflows/actions
      with:
        environment_name: dev
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
